# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chinmay/acads/assignments/DAA-Assignment-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chinmay/acads/assignments/DAA-Assignment-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chinmay/acads/assignments/DAA-Assignment-1/CMakeFiles /home/chinmay/acads/assignments/DAA-Assignment-1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chinmay/acads/assignments/DAA-Assignment-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named polygon_decomp

# Build rule for target.
polygon_decomp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 polygon_decomp
.PHONY : polygon_decomp

# fast build rule for target.
polygon_decomp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/build
.PHONY : polygon_decomp/fast

src/dcel.o: src/dcel.cc.o
.PHONY : src/dcel.o

# target to build an object file
src/dcel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/dcel.cc.o
.PHONY : src/dcel.cc.o

src/dcel.i: src/dcel.cc.i
.PHONY : src/dcel.i

# target to preprocess a source file
src/dcel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/dcel.cc.i
.PHONY : src/dcel.cc.i

src/dcel.s: src/dcel.cc.s
.PHONY : src/dcel.s

# target to generate assembly for a file
src/dcel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/dcel.cc.s
.PHONY : src/dcel.cc.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cc.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/utils.cc.o
.PHONY : src/utils.cc.o

src/utils.i: src/utils.cc.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/utils.cc.i
.PHONY : src/utils.cc.i

src/utils.s: src/utils.cc.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon_decomp.dir/build.make CMakeFiles/polygon_decomp.dir/src/utils.cc.s
.PHONY : src/utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... polygon_decomp"
	@echo "... src/dcel.o"
	@echo "... src/dcel.i"
	@echo "... src/dcel.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

